In [13]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

In [15]:
df=pd.read_csv("/content/area,bedroom,price.csv")

In [16]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  680000
4  4000      5.0    8  725000

In [18]:
import math
median_bedroom=math.floor(df.bedroom.median())
median_bedroom

3

In [20]:
df.bedroom=df.bedroom.fillna(median_bedroom)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  680000
4  4000      5.0    8  725000

In [22]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [25]:
reg.coef_

array([  143.625, -6762.5  ,   337.5  ])

In [29]:
reg.intercept_

173112.5

In [31]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([597200.])

In [32]:
143.625*3000+-6762.5*3+337.5*40+173112.5

597200.0

In [33]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([506812.5])